### ISSUE TITLE
invalid byte sequence error

### ISSUE THREAD

**Issue by shawnwall** [dcordero/Rubustrings#1] opened 2014-10-31 14:16 UTC
Even when processing a valid file (bulgarian), I am getting this error:

Processing file: "Localizable.strings"

/usr/local/bin/rubustrings:24:in `gsub': invalid byte sequence in UTF-8 (ArgumentError)
    from /usr/local/bin/rubustrings:24:in`remove_comments_and_empty_lines'
    from /usr/local/bin/rubustrings:80:in `validate_localizable_string_file'
    from /usr/local/bin/rubustrings:94:in`block in <main>'
    from /usr/local/bin/rubustrings:92:in `each'
    from /usr/local/bin/rubustrings:92:in`<main>'

I am by no means knowledgeable of ruby, but perhaps something you are using only works with utf-8?

**Comment by dcordero** [comment] 2014-11-05 11:07
Yes, it definitely looks like bad encoding assumption. I will take a look to it. Could you provide a Localizable.strings file to be able to reproduce the error? I am afraid I don't have any non utf-8 strings file in my projects.

Thanks a lot for the report @shawnwall

**Comment by shawnwall** [comment] 2014-11-05 12:23
Here you go, simply creating a localized strings with just this one string alone will do it:

"Accept" = "Приеми";

**Comment by wiz78** [comment] 2015-01-09 19:38
Apple recommends to use UTF-16 for Localizable.strings, not UTF-8: https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/LoadingResources/Strings/Strings.html

You can fix the script changing the open_and_read_file function like this:

``` ruby
def open_and_read_file(file_name)
  File.open(file_name, 'rb:utf-16:utf-8').read if File.exist?(file_name)
end
```

**Comment by shawnwall** [comment] 2015-01-12 14:42
pull req created with the mentioned change

**Comment by dcordero** [comment] 2015-01-12 14:45
Thanks a lot @shawnwall and @wiz78  . Merged

**Closed as completed by dcordero** 2015-01-12 14:45 UTC
Labels: bug
